CREATE TABLE blog (
   id int(11) NOT NULL auto_increment,
   title varchar(100) NOT NULL,
   text longtext NOT NULL,
   image varchar(100) NULL,
   movie varchar(100) NULL,
   PRIMARY KEY (id)
 );
 INSERT INTO blog (title, text)
     VALUES  ('Lorem ipsum',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin urna sem, tempus non lacus et, malesuada semper elit. Sed sed euismod augue. Vestibulum at erat magna. Donec non rhoncus velit. Sed in turpis quis mauris lobortis porta. Nunc commodo lectus sem, in pellentesque magna sodales in. Aenean fringilla ornare feugiat. Donec feugiat tristique neque, ut convallis urna mollis nec. Vivamus vitae ligula eu leo consequat varius. Aenean mattis auctor felis, in venenatis augue pretium ac. Aliquam non pretium turpis. Nulla posuere metus nisi, eu facilisis purus ultrices ac. Donec tristique justo et lorem euismod, ac volutpat lorem ultricies.');
 INSERT INTO blog (title, text)
     VALUES  ('dolor sit amet',  'Proin venenatis lacus id pretium dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam eget venenatis leo. Aenean suscipit magna sit amet nibh dapibus tempus. Nunc quis tristique nibh. Mauris mi neque, faucibus non luctus quis, suscipit fermentum elit. Cras egestas egestas elementum. Duis quis nulla vel eros sagittis dapibus.');
 INSERT INTO blog (title, text)
     VALUES  ('consectetur adipiscing elit',  'Vivamus cursus est vitae ante finibus imperdiet. Aliquam commodo, est quis tempor faucibus, urna nunc viverra risus, nec cursus dui justo at mauris. In sit amet maximus neque. In ligula ex, finibus eu arcu id, mollis feugiat justo. Donec elementum nisi non urna porta, ac malesuada dolor placerat. Sed pellentesque iaculis dolor. Duis tincidunt urna purus, et luctus velit mollis vel. Nullam tincidunt tellus vel posuere imperdiet.');
 INSERT INTO blog (title, text)
     VALUES  ('Proin urna sem',  'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur ipsum nisi, efficitur sit amet vulputate ut, efficitur non libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed id ultrices dui. Proin maximus id erat eu porttitor. Maecenas molestie nibh felis, et lacinia est efficitur non. Pellentesque fringilla lacus ut massa facilisis aliquam sed et tortor. Nam ut ultricies erat, ut lobortis quam. Aenean eleifend consectetur diam in ultrices. Vestibulum tincidunt nulla elit, vitae placerat diam lobortis a. Fusce facilisis odio eu vulputate maximus. Duis et quam justo. Ut eget lacinia sapien, sed molestie enim. Phasellus mollis odio id odio venenatis fringilla.');
 INSERT INTO blog (title, text)
     VALUES  ('tempus non lacus',  'Maecenas mattis purus quis lectus lacinia, sed tempus dui iaculis. Aenean tincidunt maximus eros sit amet tempus. Vivamus vel libero augue. Mauris sem risus, condimentum suscipit nulla vel, tristique semper ligula. Mauris vulputate justo ac egestas ultricies. Ut eu auctor risus. Praesent at rhoncus odio, sit amet porta nibh. Mauris tortor mi, pretium quis tortor sed, tempor bibendum lacus.');
INSERT INTO blog (title, text)
	     VALUES  ('tempus non lacus',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin urna sem, tempus non lacus et, malesuada semper elit. Sed sed euismod augue. Vestibulum at erat magna. Donec non rhoncus velit. Sed in turpis quis mauris lobortis porta. Nunc commodo lectus sem, in pellentesque magna sodales in. Aenean fringilla ornare feugiat. Donec feugiat tristique neque, ut convallis urna mollis nec. Vivamus vitae ligula eu leo consequat varius. Aenean mattis auctor felis, in venenatis augue pretium ac. Aliquam non pretium turpis. Nulla posuere metus nisi, eu facilisis purus ultrices ac. Donec tristique justo et lorem euismod, ac volutpat lorem ultricies.

Proin venenatis lacus id pretium dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam eget venenatis leo. Aenean suscipit magna sit amet nibh dapibus tempus. Nunc quis tristique nibh. Mauris mi neque, faucibus non luctus quis, suscipit fermentum elit. Cras egestas egestas elementum. Duis quis nulla vel eros sagittis dapibus.

Vivamus cursus est vitae ante finibus imperdiet. Aliquam commodo, est quis tempor faucibus, urna nunc viverra risus, nec cursus dui justo at mauris. In sit amet maximus neque. In ligula ex, finibus eu arcu id, mollis feugiat justo. Donec elementum nisi non urna porta, ac malesuada dolor placerat. Sed pellentesque iaculis dolor. Duis tincidunt urna purus, et luctus velit mollis vel. Nullam tincidunt tellus vel posuere imperdiet.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur ipsum nisi, efficitur sit amet vulputate ut, efficitur non libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed id ultrices dui. Proin maximus id erat eu porttitor. Maecenas molestie nibh felis, et lacinia est efficitur non. Pellentesque fringilla lacus ut massa facilisis aliquam sed et tortor. Nam ut ultricies erat, ut lobortis quam. Aenean eleifend consectetur diam in ultrices. Vestibulum tincidunt nulla elit, vitae placerat diam lobortis a. Fusce facilisis odio eu vulputate maximus. Duis et quam justo. Ut eget lacinia sapien, sed molestie enim. Phasellus mollis odio id odio venenatis fringilla.

Maecenas mattis purus quis lectus lacinia, sed tempus dui iaculis. Aenean tincidunt maximus eros sit amet tempus. Vivamus vel libero augue. Mauris sem risus, condimentum suscipit nulla vel, tristique semper ligula. Mauris vulputate justo ac egestas ultricies. Ut eu auctor risus. Praesent at rhoncus odio, sit amet porta nibh. Mauris tortor mi, pretium quis tortor sed, tempor bibendum lacus.');
