<?php
//$this->headLink()->appendStylesheet('/css/opmaak.css');
$form = $this->form;
$form->setAttribute('action', $this->url('blog', array('action' => 'add')));
$form->prepare();
$title = $form->get('Title');
$text = $form->get('Text');
$fileElement = $form->get('Image');



?>
<div>
    <div>
        <div>
            <div>
                <h3>Add blog item</h3>
            </div>
            <div>
            	<?php 
            	echo $this->form()->openTag($form);
				echo $this->formHidden($form->get('id')); 
            	
            	?>
                <table>
                    <tbody>
                    <tr>
                       <td><?php echo $this->formLabel($title);?></td>
						<td><?php echo $this->formInput( $form->get('Title'));?></td>
						<td><?php 	echo $this->formElementErrors($title);?></td>
                    </tr>
                   
                    <tr>
                       <td><?php echo $this->formLabel($text);?></td>
						<td><?php echo $this->formTextArea($text);?></td>
						<td><?php 	echo $this->formElementErrors($text);?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->formLabel($fileElement);?></td>
						<td><?php echo $this->formFile($fileElement);?></td>
						<td><?php 	echo $this->formElementErrors($fileElement);?></td>
                    </tr>
                    <tr>
                        <td colspan="3"><?php echo $this->formSubmit($form->get('submit')); ?></td>
                    </tr>
                    </tbody>
                </table>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div> 




