<?php
$title = 'Verwijder blog';
$id = (int) $blog->getId();
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Weet u zeker dat u het blog wil verwijderen?
 </p>
 <?php
 $url = $this->url('blog', array(
     'action' => 'delete',
     'id'     => $id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo $id ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>