<div>
    <div>
        <div>
            <div>
                <h3><?php echo $blog->getTitle(); ?></h3>
            </div>
            <div>

                <?php if (isset($blog)) : ?>
                <table>
                    <tbody>
                    <tr>
                        <td><?php echo $blog->getText(); ?></td>
                         <td>
                        	<?php
                        	if($blog->getImage()){
                        		?>
                        		<img src="<?php echo '/Assets/'.$blog->getImage(); ?>" height="150 width="75" alt="<?php echo $blog->getTitle(); ?>">
                        		<?php
							}
							else {
								?>
                        		<img src="<?php echo '/Assets/geen_foto_beschikbaar.jpg'?>" height="100" width="100" alt="no image">
                        		<?php
							}
                    		?>
                    	</td>
                    </tr>
                    <tr>
                    	<td>
                            <a href="<?php echo $this->url('blog', array('action'=>'edit', 'id' => $blog->getId()));?>">Edit</a> |
                            <a href="<?php echo $this->url('blog', array('action'=>'delete', 'id' => $blog->getId()));?>">Delete</a>
                        </td>
                      
                    </tr>
                    </tbody>
                </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>