<?php
$form = $this->form;
$form->setAttribute('action', $this->url('blog', array('action' => 'edit', 'id' => $id)));
$form->prepare();
$title = $form->get('Title');
$text = $form->get('Text');
$fileElement = $form->get('Image');
?>
<div>
    <div>
        <div>
            <div>
                <h3>Add blog item</h3>
            </div>
            <div>
            	<?php 
            	echo $this->form()->openTag($form);
            	?>
                <table>
                    <tbody>
                    <tr>
                       <td><?php echo $this->formLabel($title);?></td>
						<td><input type="text" name="Title" value="<?php echo $blog->getTitle()?>"></td>
						<td><?php echo $this->formElementErrors($title);?></td>
                    </tr>
                   
                    <tr>
                       <td><?php echo $this->formLabel($text);?></td>
						<td><textarea  rows="20" cols="40" name="Text" ><?php echo $blog->getText()?></textarea></td>
						<td><?php echo $this->formElementErrors($text);?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->formLabel($fileElement);?></td>
						<td><?php echo $this->formFile($fileElement);?></td>
						<td><?php echo $this->formElementErrors($fileElement);?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->formSubmit($form->get('submit')); ?></td>
                    </tr>
                    </tbody>
                </table>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div> 




